name: Build Releases

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write  # This is required for creating releases

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            output_name: greetings-linux
            asset_name: greetings-linux
          - os: windows-latest
            output_name: greetings-windows
            asset_name: greetings-windows.exe
          - os: macos-latest
            output_name: greetings-macos
            asset_name: greetings-macos

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'  # Updated to Python 3.10 for match/case support
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller requests pytz
        
    - name: Build with PyInstaller
      run: pyinstaller --onefile --name ${{ matrix.output_name }} main.py
      shell: bash
        
    - name: Upload Release Asset
      uses: softprops/action-gh-release@v1
      with:
        files: dist/${{ matrix.asset_name }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 