name: Build Releases

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            output_name: greetings-linux
            asset_name: greetings-linux
          - os: windows-latest
            output_name: greetings-windows
            asset_name: greetings-windows.exe
          - os: macos-latest
            output_name: greetings-macos
            asset_name: greetings-macos

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller requests pytz
        
    - name: Build with PyInstaller
      run: |
        if [ "${{ matrix.os }}" = "windows-latest" ]; then
          pyinstaller --onefile --add-data "bin/windows;bin/windows" --name ${{ matrix.output_name }} main.py
        elif [ "${{ matrix.os }}" = "macos-latest" ]; then
          pyinstaller --onefile --add-data "bin/macOS:bin/macOS" --name ${{ matrix.output_name }} main.py
        else
          pyinstaller --onefile --add-data "bin/linux:bin/linux" --name ${{ matrix.output_name }} main.py
        fi
      shell: bash
        
    - name: Upload Release Asset
      uses: softprops/action-gh-release@v1
      with:
        files: dist/${{ matrix.asset_name }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 